"""Vectorization Agent — chunking, text record upsert, RAG retrieval via Pinecone Integrated Embeddings."""
import structlog
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.orm import Post, VectorMeta
from app.services.vector_db import upsert_text_record, query_text

logger = structlog.get_logger()

CHUNK_SIZE = 500  # characters per chunk


class VectorizationAgent:
    """Stores post text in Pinecone (embedding generated by Pinecone) and retrieves RAG context."""

    async def vectorize_post(self, post: Post, db: AsyncSession) -> list[str]:
        """Chunk post content and upsert each chunk as a text record."""
        if not post.content:
            return []

        chunks = self._chunk_text(post.content, CHUNK_SIZE)
        vector_ids = []

        for i, chunk in enumerate(chunks):
            vector_id = f"post:{post.id}:chunk:{i}"
            metadata = {
                "user_id": post.user_id,
                "post_id": post.id,
                "platform": post.platform,
                "chunk_index": i,
                "content_preview": chunk[:200],
                "likes": (post.metrics or {}).get("likes", 0),
                "comments": (post.metrics or {}).get("comments", 0),
            }

            success = await upsert_text_record(
                record_id=vector_id,
                text=chunk,
                metadata=metadata,
                namespace=post.user_id,
            )

            if success:
                vm = VectorMeta(
                    user_id=post.user_id,
                    object_type="post",
                    object_id=post.id,
                    vector_id=vector_id,
                    extra_metadata=metadata,
                )
                db.add(vm)
                vector_ids.append(vector_id)

        await db.flush()
        logger.info("post_vectorized", post_id=post.id, chunks=len(vector_ids))
        return vector_ids

    async def vectorize_user_posts(self, user_id: str, db: AsyncSession) -> dict:
        """Vectorize all unvectorized posts for a user."""
        result = await db.execute(
            select(Post).where(
                Post.user_id == user_id,
                Post.content.isnot(None),
            ).limit(500)
        )
        posts = result.scalars().all()

        total_vectors = 0
        for post in posts:
            # Skip if already vectorized
            existing = await db.execute(
                select(VectorMeta).where(
                    VectorMeta.object_id == post.id,
                    VectorMeta.object_type == "post",
                )
            )
            if existing.scalar_one_or_none():
                continue

            ids = await self.vectorize_post(post, db)
            total_vectors += len(ids)

        return {"user_id": user_id, "posts_processed": len(posts), "vectors_created": total_vectors}

    async def get_rag_context(
        self,
        user_id: str,
        query: str,
        top_k: int = 5,
    ) -> str:
        """Retrieve relevant past content using Pinecone text search."""
        try:
            results = await query_text(
                query=query,
                top_k=top_k,
                namespace=user_id,
                filter={"user_id": user_id},
            )
        except Exception as exc:
            logger.warning("rag_query_failed", error=str(exc))
            return ""

        if not results:
            return ""

        context_parts = []
        for r in results:
            meta = r.get("metadata", {})
            content = meta.get("content_preview", "")
            platform = meta.get("platform", "unknown")
            score = r.get("score", 0)
            context_parts.append(f"[{platform}, relevance {score:.2f}] {content}")

        return "\n\n".join(context_parts)

    def _chunk_text(self, text: str, chunk_size: int) -> list[str]:
        """Simple character-based chunking with overlap."""
        overlap = 50
        chunks = []
        start = 0
        while start < len(text):
            end = min(start + chunk_size, len(text))
            chunks.append(text[start:end])
            start = end - overlap if end < len(text) else end
        return chunks


vectorization_agent = VectorizationAgent()
